# -*- coding: utf-8 -*-
"""BreatheSafe_ML_Prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GANuSu77laTt6Fo8NnI6B87nSuXcNCnW

#BreatheSafe: AI-Powered Air Quality Prediction
### Hackathon Prototype - Jupyter/Colab Version
"""

import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

# Synthetic dataset generation
np.random.seed(42)
n_samples = 5000
dates = pd.date_range(datetime(2022,1,1), periods=n_samples, freq='D')
locations = ['Asia', 'Europe', 'Africa', 'North America', 'South America', 'Australia']

data = {
    'date': np.random.choice(dates, n_samples),
    'location': np.random.choice(locations, n_samples),
    'pm25': np.random.uniform(10, 200, n_samples),
    'pm10': np.random.uniform(20, 300, n_samples),
    'no2': np.random.uniform(5, 80, n_samples),
    'o3': np.random.uniform(10, 120, n_samples),
    'co': np.random.uniform(0.1, 3, n_samples),
    'temperature': np.random.uniform(5, 40, n_samples),
    'humidity': np.random.uniform(20, 90, n_samples),
    'wind_speed': np.random.uniform(0.5, 10, n_samples)
}

df = pd.DataFrame(data)
df['aqi'] = (0.5*df['pm25'] + 0.2*df['pm10'] + 0.1*df['no2'] + 0.1*df['o3'] + 10*df['co'] - 0.3*df['wind_speed'] - 0.2*df['humidity']/10).clip(0, 500)
df.head()

# Visualizations
plt.figure(figsize=(8,5))
sns.histplot(df['aqi'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Air Quality Index (AQI)')
plt.show()

plt.figure(figsize=(8,5))
sns.heatmap(df[['pm25','pm10','no2','o3','co','temperature','humidity','wind_speed','aqi']].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Model Training
features = ['pm25','pm10','no2','o3','co','temperature','humidity','wind_speed']
X = df[features]
y = df['aqi']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
print(f'RMSE: {rmse:.2f}, R²: {r2:.3f}')

# Example prediction
example = pd.DataFrame([{
    'pm25':80,'pm10':120,'no2':40,'o3':60,'co':1.2,
    'temperature':28,'humidity':60,'wind_speed':2
}])

predicted_aqi = model.predict(example)[0]
print('Predicted AQI:', predicted_aqi)